Set build date from SOURCE_DATE_EPOCH
prometheus/promu pull request #230
Opened 2022-04-27 08:10 UTC by witekest

Allow to override build date with SOURCE_DATE_EPOCH
in order to make builds reproducible.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.

This PR was done while working on [reproducible builds for
openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds).

Signed-off-by: Witek Bedyk <witold.bedyk@suse.com>

2022-05-09 06:44 UTC, bmwiedemann commented on cmd/build.go
> +		} else {
This is IETF style wording and not a `MUST`, though.

2022-05-09 08:19 UTC, SuperQ requested changes

2022-05-09 08:19 UTC, SuperQ commented on cmd/build.go
> +		} else {
I agree with @matthiasr here. If we want to follow this spec, we should validate user input and fast-fail on bad input for predictable behavior.

2022-05-10 14:54 UTC, witekest commented on cmd/build.go
> +		} else {
Agreed, I check if the value is set and if can be parsed correctly now.

2022-05-13 07:01 UTC, SuperQ approved these changes
LGTM

2022-05-20 16:59 UTC, matthiasr approved these changes

2022-05-20 18:51 UTC, merged