Draft:Add codesign utility function
prometheus/promu pull request #284
Opened 2024-02-15 19:49 UTC by gitperr

Calls on `rcodesign` to code sign a target binary.

TODO:
- [ ] Add tests
- [ ] Other, based on feedback

2024-02-17 19:21 UTC, gitperr commented
@SuperQ wanna take a look?

2024-02-18 11:29 UTC, SuperQ requested changes
Minor nit, otherwise LGTM.

We're also going to need to plumb this into our CI templates so that it's done automatically.

2024-02-18 11:29 UTC, SuperQ commented on cmd/codesign.go
> +// Copyright © 2016 Prometheus Team
New file needs current year.
```suggestion
// Copyright © 2024 Prometheus Team
```

2024-02-18 13:56 UTC, gitperr commented on cmd/codesign.go
> +// Copyright © 2016 Prometheus Team
Updated to 2024

2024-02-18 13:58 UTC, gitperr commented
Squashed, will make changes to https://github.com/prometheus/node_exporter/pull/2916 as well to accompany this.

2024-02-18 14:10 UTC, gitperr commented
Updated README as well now. And squashed again. Should be good to go, please take another look.

This should be merged before https://github.com/prometheus/node_exporter/pull/2916 to make pipelines start working properly with `promu codesign`

2024-02-18 14:55 UTC, SuperQ approved these changes
LGTM

2024-03-19 21:12 UTC, gitperr commented
@roidelapluie does this PR look good?

2024-04-14 14:34 UTC, gitperr commented
Is there anyone else we can ask review from? If roidelapluie is busy, maybe someone else could take a look?

2024-04-14 15:01 UTC, merged